# -*- coding: utf-8 -*-
"""test_fn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ps8JPX8OwQqo0NTsEXP46n5s0DeN7GMV
"""

def test_fn(data_loader,model):
  model.eval()
  test_loss =0.0
  test_iou =0.0
  test_dice_coef = 0.0
  test_accuracy = 0.0
  with torch.no_grad():
    for images,masks in tqdm(data_loader):
      images = images.to(device)
      masks = masks.to(device)
      logits = model(images)
      # loss = loss_function(logits,masks)
      loss = dice_loss(logits,masks)
      test_iou+=iou_metric(logits,masks).detach().cpu().numpy()
      test_dice_coef+= dice_coef_metric(logits,masks).detach().cpu().numpy()
      test_accuracy+= accuracy_metric(logits,masks).detach().cpu().numpy()
      test_loss+=loss.detach().cpu().numpy()
  return test_loss/len(data_loader),test_dice_coef/len(data_loader),test_accuracy/len(data_loader),test_iou/len(data_loader)